### ISSUE TITLE
okconfig rpm dependancy problem

### ISSUE THREAD

**Issue by richard-allen** [opinkerfi/okconfig#75]
OMD 1.20 includes Nagios.  okconfig rpm for rhel/centos depends on installing the base Nagios rpm's as well.     Perhaps nagios should be dropped as a RPM dependancy as nobody would install okconfig without having nagios already installed.

**Comment by ashirel** [comment]
i've installed okconfig from sourceon debian v7 wheezy according to the instructions in
https://github.com/opinkerfi/okconfig#installing-on-rhelcentos
with  nagios3.5.1 and adagios1.4 already installed and running.
the okconfig install seemed successful because the verify succeeded.
however, the adagios 'config health'  reports 'false for 'OKConfig is installed and working'.
where shall i look to determine why adagios reports thusly?

**Comment by gardart** [comment]
Fixed in 1.3.2-1 - Nagios dependency removed
